var alabama =
[{"State":"Alabama","County":"Autauga","City":"Autaugaville"},
{"State":"Alabama","County":"Autauga ","City":"Billingsley"},
{"State":"Alabama","County":"Autauga ","City":"Millbrook city"},
{"State":"Alabama","County":"Autauga ","City":"Prattville city"},
{"State":"Alabama","County":"Baldwin ","City":"Bay Minette city"},
{"State":"Alabama","County":"Baldwin ","City":"Daphne city"},
{"State":"Alabama","County":"Baldwin ","City":"Elberta"},
{"State":"Alabama","County":"Baldwin ","City":"Fairhope city"},
{"State":"Alabama","County":"Baldwin ","City":"Foley city"},
{"State":"Alabama","County":"Baldwin ","City":"Gulf Shores city"},
{"State":"Alabama","County":"Baldwin ","City":"Loxley"},
{"State":"Alabama","County":"Baldwin ","City":"Magnolia Springs"},
{"State":"Alabama","County":"Baldwin ","City":"Orange Beach city"},
{"State":"Alabama","County":"Baldwin ","City":"Perdido Beach"},
{"State":"Alabama","County":"Baldwin ","City":"Robertsdale city"},
{"State":"Alabama","County":"Baldwin ","City":"Silverhill"},
{"State":"Alabama","County":"Baldwin ","City":"Spanish Fort city"},
{"State":"Alabama","County":"Baldwin ","City":"Summerdale"},
{"State":"Alabama","County":"Barbour ","City":"Bakerhill"},
{"State":"Alabama","County":"Barbour ","City":"Blue Springs"},
{"State":"Alabama","County":"Barbour ","City":"Clayton"},
{"State":"Alabama","County":"Barbour ","City":"Clio city"},
{"State":"Alabama","County":"Barbour ","City":"Eufaula city"},
{"State":"Alabama","County":"Barbour ","City":"Louisville"},
{"State":"Alabama","County":"Bibb","City":"Brent city"},
{"State":"Alabama","County":"Bibb","City":"Centreville city"},
{"State":"Alabama","County":"Bibb","City":"Vance"},
{"State":"Alabama","County":"Bibb","City":"West Blocton"},
{"State":"Alabama","County":"Bibb","City":"Woodstock"},
{"State":"Alabama","County":"Blount","City":"Allgood"},
{"State":"Alabama","County":"Blount","City":"Altoona"},
{"State":"Alabama","County":"Blount","City":"Blountsville"},
{"State":"Alabama","County":"Blount","City":"Cleveland"},
{"State":"Alabama","County":"Blount","City":"County Line"},
{"State":"Alabama","County":"Blount","City":"Garden City"},
{"State":"Alabama","County":"Blount","City":"Hayden"},
{"State":"Alabama","County":"Blount","City":"Highland Lake"},
{"State":"Alabama","County":"Blount","City":"Locust Fork"},
{"State":"Alabama","County":"Blount","City":"Nectar"},
{"State":"Alabama","County":"Blount","City":"Oneonta city"},
{"State":"Alabama","County":"Blount","City":"Rosa"},
{"State":"Alabama","County":"Blount","City":"Snead"},
{"State":"Alabama","County":"Blount","City":"Susan Moore"},
{"State":"Alabama","County":"Blount","City":"Trafford"},
{"State":"Alabama","County":"Bullock","City":"Midway"},
{"State":"Alabama","County":"Bullock","City":"Union Springs city"},
{"State":"Alabama","County":"Butler ","City":"Georgiana"},
{"State":"Alabama","County":"Butler ","City":"Greenville city"},
{"State":"Alabama","County":"Butler ","City":"McKenzie"},
{"State":"Alabama","County":"Calhoun ","City":"Anniston city"},
{"State":"Alabama","County":"Calhoun ","City":"Glencoe city"},
{"State":"Alabama","County":"Calhoun ","City":"Hobson City"},
{"State":"Alabama","County":"Calhoun ","City":"Jacksonville city"},
{"State":"Alabama","County":"Calhoun ","City":"Ohatchee"},
{"State":"Alabama","County":"Calhoun ","City":"Oxford city"},
{"State":"Alabama","County":"Calhoun ","City":"Piedmont city"},
{"State":"Alabama","County":"Calhoun ","City":"Southside city"},
{"State":"Alabama","County":"Calhoun ","City":"Weaver city"},
{"State":"Alabama","County":"Chambers ","City":"Cusseta"},
{"State":"Alabama","County":"Chambers ","City":"Five Points"},
{"State":"Alabama","County":"Chambers ","City":"La Fayette city"},
{"State":"Alabama","County":"Chambers ","City":"Lanett city"},
{"State":"Alabama","County":"Chambers ","City":"Valley city"},
{"State":"Alabama","County":"Chambers ","City":"Waverly"},
{"State":"Alabama","County":"Cherokee ","City":"Cedar Bluff"},
{"State":"Alabama","County":"Cherokee ","City":"Centre city"},
{"State":"Alabama","County":"Cherokee ","City":"Collinsville"},
{"State":"Alabama","County":"Cherokee ","City":"Gaylesville"},
{"State":"Alabama","County":"Cherokee ","City":"Leesburg"},
{"State":"Alabama","County":"Cherokee ","City":"Piedmont city"},
{"State":"Alabama","County":"Cherokee ","City":"Sand Rock"},
{"State":"Alabama","County":"Chilton ","City":"Calera city"},
{"State":"Alabama","County":"Chilton ","City":"Clanton city"},
{"State":"Alabama","County":"Chilton ","City":"Jemison city"},
{"State":"Alabama","County":"Chilton ","City":"Maplesville"},
{"State":"Alabama","County":"Chilton ","City":"Thorsby"},
{"State":"Alabama","County":"Choctaw ","City":"Butler"},
{"State":"Alabama","County":"Choctaw ","City":"Gilbertown"},
{"State":"Alabama","County":"Choctaw ","City":"Lisman"},
{"State":"Alabama","County":"Choctaw ","City":"Needham"},
{"State":"Alabama","County":"Choctaw ","City":"Pennington"},
{"State":"Alabama","County":"Choctaw ","City":"Silas"},
{"State":"Alabama","County":"Choctaw ","City":"Toxey"},
{"State":"Alabama","County":"Clarke ","City":"Coffeeville"},
{"State":"Alabama","County":"Clarke ","City":"Fulton"},
{"State":"Alabama","County":"Clarke ","City":"Grove Hill"},
{"State":"Alabama","County":"Clarke ","City":"Jackson city"},
{"State":"Alabama","County":"Clarke ","City":"Thomasville city"},
{"State":"Alabama","County":"Clay ","City":"Ashland"},
{"State":"Alabama","County":"Clay ","City":"Lineville city"},
{"State":"Alabama","County":"Cleburne ","City":"Edwardsville"},
{"State":"Alabama","County":"Cleburne ","City":"Fruithurst"},
{"State":"Alabama","County":"Cleburne ","City":"Heflin city"},
{"State":"Alabama","County":"Cleburne ","City":"Ranburne"},
{"State":"Alabama","County":"Coffee ","City":"Elba city"},
{"State":"Alabama","County":"Coffee ","City":"Enterprise city"},
{"State":"Alabama","County":"Coffee ","City":"Kinston"},
{"State":"Alabama","County":"Coffee ","City":"New Brockton"},
{"State":"Alabama","County":"Colbert ","City":"Cherokee"},
{"State":"Alabama","County":"Colbert ","City":"Leighton"},
{"State":"Alabama","County":"Colbert ","City":"Littleville"},
{"State":"Alabama","County":"Colbert ","City":"Muscle Shoals city"},
{"State":"Alabama","County":"Colbert ","City":"Sheffield city"},
{"State":"Alabama","County":"Colbert ","City":"Tuscumbia city"},
{"State":"Alabama","County":"Conecuh ","City":"Castleberry"},
{"State":"Alabama","County":"Conecuh ","City":"Evergreen city"},
{"State":"Alabama","County":"Conecuh ","City":"McKenzie"},
{"State":"Alabama","County":"Conecuh ","City":"Repton"},
{"State":"Alabama","County":"Coosa ","City":"Goodwater"},
{"State":"Alabama","County":"Coosa ","City":"Kellyton"},
{"State":"Alabama","County":"Coosa ","City":"Rockford"},
{"State":"Alabama","County":"Covington ","City":"Andalusia city"},
{"State":"Alabama","County":"Covington ","City":"Babbie"},
{"State":"Alabama","County":"Covington ","City":"Carolina"},
{"State":"Alabama","County":"Covington ","City":"Florala"},
{"State":"Alabama","County":"Covington ","City":"Gantt"},
{"State":"Alabama","County":"Covington ","City":"Heath"},
{"State":"Alabama","County":"Covington ","City":"Horn Hill"},
{"State":"Alabama","County":"Covington ","City":"Libertyville"},
{"State":"Alabama","County":"Covington ","City":"Lockhart"},
{"State":"Alabama","County":"Covington ","City":"Onycha"},
{"State":"Alabama","County":"Covington ","City":"Opp city"},
{"State":"Alabama","County":"Covington ","City":"Red Level"},
{"State":"Alabama","County":"Covington ","City":"River Falls"},
{"State":"Alabama","County":"Covington ","City":"Sanford"},
{"State":"Alabama","County":"Crenshaw ","City":"Brantley"},
{"State":"Alabama","County":"Crenshaw ","City":"Dozier"},
{"State":"Alabama","County":"Crenshaw ","City":"Glenwood"},
{"State":"Alabama","County":"Crenshaw ","City":"Luverne city"},
{"State":"Alabama","County":"Crenshaw ","City":"Petrey"},
{"State":"Alabama","County":"Crenshaw ","City":"Rutledge"},
{"State":"Alabama","County":"Cullman ","City":"Arab city"},
{"State":"Alabama","County":"Cullman ","City":"Baileyton"},
{"State":"Alabama","County":"Cullman ","City":"Colony"},
{"State":"Alabama","County":"Cullman ","City":"Cullman city"},
{"State":"Alabama","County":"Cullman ","City":"Dodge City"},
{"State":"Alabama","County":"Cullman ","City":"Fairview"},
{"State":"Alabama","County":"Cullman ","City":"Garden City"},
{"State":"Alabama","County":"Cullman ","City":"Good Hope"},
{"State":"Alabama","County":"Cullman ","City":"Hanceville city"},
{"State":"Alabama","County":"Cullman ","City":"Holly Pond"},
{"State":"Alabama","County":"Cullman ","City":"South Vinemont"},
{"State":"Alabama","County":"Cullman ","City":"West Point"},
{"State":"Alabama","County":"Dale ","City":"Ariton"},
{"State":"Alabama","County":"Dale ","City":"Clayhatchee"},
{"State":"Alabama","County":"Dale ","City":"Daleville city"},
{"State":"Alabama","County":"Dale ","City":"Dothan city"},
{"State":"Alabama","County":"Dale ","City":"Enterprise city"},
{"State":"Alabama","County":"Dale ","City":"Grimes"},
{"State":"Alabama","County":"Dale ","City":"Level Plains"},
{"State":"Alabama","County":"Dale ","City":"Midland City"},
{"State":"Alabama","County":"Dale ","City":"Napier Field"},
{"State":"Alabama","County":"Dale ","City":"Newton"},
{"State":"Alabama","County":"Dale ","City":"Ozark city"},
{"State":"Alabama","County":"Dale ","City":"Pinckard"},
{"State":"Alabama","County":"Dallas ","City":"Orrville"},
{"State":"Alabama","County":"Dallas ","City":"Selma city"},
{"State":"Alabama","County":"Dallas ","City":"Valley Grande city"},
{"State":"Alabama","County":"DeKalb ","City":"Collinsville"},
{"State":"Alabama","County":"DeKalb ","City":"Crossville"},
{"State":"Alabama","County":"DeKalb ","City":"Fort Payne city"},
{"State":"Alabama","County":"DeKalb ","City":"Fyffe"},
{"State":"Alabama","County":"DeKalb ","City":"Geraldine"},
{"State":"Alabama","County":"DeKalb ","City":"Hammondville"},
{"State":"Alabama","County":"DeKalb ","City":"Henagar city"},
{"State":"Alabama","County":"DeKalb ","City":"Ider"},
{"State":"Alabama","County":"DeKalb ","City":"Lakeview"},
{"State":"Alabama","County":"DeKalb ","City":"Mentone"},
{"State":"Alabama","County":"DeKalb ","City":"Pine Ridge"},
{"State":"Alabama","County":"DeKalb ","City":"Powell"},
{"State":"Alabama","County":"DeKalb ","City":"Rainsville city"},
{"State":"Alabama","County":"DeKalb ","City":"Sand Rock"},
{"State":"Alabama","County":"DeKalb ","City":"Shiloh"},
{"State":"Alabama","County":"DeKalb ","City":"Sylvania"},
{"State":"Alabama","County":"DeKalb ","City":"Valley Head"},
{"State":"Alabama","County":"Elmore ","City":"Coosada"},
{"State":"Alabama","County":"Elmore ","City":"Deatsville"},
{"State":"Alabama","County":"Elmore ","City":"Eclectic"},
{"State":"Alabama","County":"Elmore ","City":"Elmore"},
{"State":"Alabama","County":"Elmore ","City":"Millbrook city"},
{"State":"Alabama","County":"Elmore ","City":"Prattville city"},
{"State":"Alabama","County":"Elmore ","City":"Tallassee city"},
{"State":"Alabama","County":"Elmore ","City":"Wetumpka city"},
{"State":"Alabama","County":"Escambia ","City":"Atmore city"},
{"State":"Alabama","County":"Escambia ","City":"Brewton city"},
{"State":"Alabama","County":"Escambia ","City":"East Brewton city"},
{"State":"Alabama","County":"Escambia ","City":"Flomaton"},
{"State":"Alabama","County":"Escambia ","City":"Pollard"},
{"State":"Alabama","County":"Escambia ","City":"Riverview"},
{"State":"Alabama","County":"Etowah ","City":"Altoona"},
{"State":"Alabama","County":"Etowah ","City":"Attalla city"},
{"State":"Alabama","County":"Etowah ","City":"Boaz city"},
{"State":"Alabama","County":"Etowah ","City":"Gadsden city"},
{"State":"Alabama","County":"Etowah ","City":"Glencoe city"},
{"State":"Alabama","County":"Etowah ","City":"Hokes Bluff city"},
{"State":"Alabama","County":"Etowah ","City":"Rainbow City city"},
{"State":"Alabama","County":"Etowah ","City":"Reece City"},
{"State":"Alabama","County":"Etowah ","City":"Ridgeville"},
{"State":"Alabama","County":"Etowah ","City":"Sardis City"},
{"State":"Alabama","County":"Etowah ","City":"Southside city"},
{"State":"Alabama","County":"Etowah ","City":"Walnut Grove"},
{"State":"Alabama","County":"Fayette ","City":"Belk"},
{"State":"Alabama","County":"Fayette ","City":"Berry"},
{"State":"Alabama","County":"Fayette ","City":"Fayette city"},
{"State":"Alabama","County":"Fayette ","City":"Glen Allen"},
{"State":"Alabama","County":"Fayette ","City":"Gu-Win"},
{"State":"Alabama","County":"Fayette ","City":"Winfield city"},
{"State":"Alabama","County":"Franklin ","City":"Hodges"},
{"State":"Alabama","County":"Franklin ","City":"Phil Campbell"},
{"State":"Alabama","County":"Franklin ","City":"Red Bay city"},
{"State":"Alabama","County":"Franklin ","City":"Russellville city"},
{"State":"Alabama","County":"Franklin ","City":"Vina"},
{"State":"Alabama","County":"Geneva ","City":"Black"},
{"State":"Alabama","County":"Geneva ","City":"Coffee Springs"},
{"State":"Alabama","County":"Geneva ","City":"Geneva city"},
{"State":"Alabama","County":"Geneva ","City":"Hartford city"},
{"State":"Alabama","County":"Geneva ","City":"Malvern"},
{"State":"Alabama","County":"Geneva ","City":"Samson city"},
{"State":"Alabama","County":"Geneva ","City":"Slocomb city"},
{"State":"Alabama","County":"Geneva ","City":"Taylor"},
{"State":"Alabama","County":"Greene ","City":"Boligee"},
{"State":"Alabama","County":"Greene ","City":"Eutaw"},
{"State":"Alabama","County":"Greene ","City":"Forkland"},
{"State":"Alabama","County":"Greene ","City":"Union"},
{"State":"Alabama","County":"Hale ","City":"Akron"},
{"State":"Alabama","County":"Hale ","City":"Greensboro city"},
{"State":"Alabama","County":"Hale ","City":"Moundville"},
{"State":"Alabama","County":"Hale ","City":"Newbern"},
{"State":"Alabama","County":"Henry ","City":"Abbeville city"},
{"State":"Alabama","County":"Henry ","City":"Dothan city"},
{"State":"Alabama","County":"Henry ","City":"Haleburg"},
{"State":"Alabama","County":"Henry ","City":"Headland city"},
{"State":"Alabama","County":"Henry ","City":"Newville"},
{"State":"Alabama","County":"Houston ","City":"Ashford"},
{"State":"Alabama","County":"Houston ","City":"Avon"},
{"State":"Alabama","County":"Houston ","City":"Columbia"},
{"State":"Alabama","County":"Houston ","City":"Cottonwood"},
{"State":"Alabama","County":"Houston ","City":"Cowarts"},
{"State":"Alabama","County":"Houston ","City":"Dothan city"},
{"State":"Alabama","County":"Houston ","City":"Gordon"},
{"State":"Alabama","County":"Houston ","City":"Kinsey"},
{"State":"Alabama","County":"Houston ","City":"Madrid"},
{"State":"Alabama","County":"Houston ","City":"Rehobeth"},
{"State":"Alabama","County":"Houston ","City":"Taylor"},
{"State":"Alabama","County":"Houston ","City":"Webb"},
{"State":"Alabama","County":"Jackson ","City":"Bridgeport city"},
{"State":"Alabama","County":"Jackson ","City":"Dutton"},
{"State":"Alabama","County":"Jackson ","City":"Hollywood"},
{"State":"Alabama","County":"Jackson ","City":"Hytop"},
{"State":"Alabama","County":"Jackson ","City":"Langston"},
{"State":"Alabama","County":"Jackson ","City":"Paint Rock"},
{"State":"Alabama","County":"Jackson ","City":"Pisgah"},
{"State":"Alabama","County":"Jackson ","City":"Pleasant Groves"},
{"State":"Alabama","County":"Jackson ","City":"Scottsboro city"},
{"State":"Alabama","County":"Jackson ","City":"Section"},
{"State":"Alabama","County":"Jackson ","City":"Skyline"},
{"State":"Alabama","County":"Jackson ","City":"Stevenson city"},
{"State":"Alabama","County":"Jackson ","City":"Woodville"},
{"State":"Alabama","County":"Jefferson ","City":"Adamsville city"},
{"State":"Alabama","County":"Jefferson ","City":"Argo"},
{"State":"Alabama","County":"Jefferson ","City":"Bessemer city"},
{"State":"Alabama","County":"Jefferson ","City":"Birmingham city"},
{"State":"Alabama","County":"Jefferson ","City":"Brighton city"},
{"State":"Alabama","County":"Jefferson ","City":"Brookside"},
{"State":"Alabama","County":"Jefferson ","City":"Cardiff"},
{"State":"Alabama","County":"Jefferson ","City":"Center Point city"},
{"State":"Alabama","County":"Jefferson ","City":"Clay city"},
{"State":"Alabama","County":"Jefferson ","City":"County Line"},
{"State":"Alabama","County":"Jefferson ","City":"Fairfield city"},
{"State":"Alabama","County":"Jefferson ","City":"Fultondale city"},
{"State":"Alabama","County":"Jefferson ","City":"Gardendale city"},
{"State":"Alabama","County":"Jefferson ","City":"Graysville city"},
{"State":"Alabama","County":"Jefferson ","City":"Helena city"},
{"State":"Alabama","County":"Jefferson ","City":"Homewood city"},
{"State":"Alabama","County":"Jefferson ","City":"Hoover city"},
{"State":"Alabama","County":"Jefferson ","City":"Hueytown city"},
{"State":"Alabama","County":"Jefferson ","City":"Irondale city"},
{"State":"Alabama","County":"Jefferson ","City":"Kimberly"},
{"State":"Alabama","County":"Jefferson ","City":"Leeds city"},
{"State":"Alabama","County":"Jefferson ","City":"Lipscomb city"},
{"State":"Alabama","County":"Jefferson ","City":"Maytown"},
{"State":"Alabama","County":"Jefferson ","City":"Midfield city"},
{"State":"Alabama","County":"Jefferson ","City":"Morris"},
{"State":"Alabama","County":"Jefferson ","City":"Mountain Brook city"},
{"State":"Alabama","County":"Jefferson ","City":"Mulga"},
{"State":"Alabama","County":"Jefferson ","City":"North Johns"},
{"State":"Alabama","County":"Jefferson ","City":"Pinson city"},
{"State":"Alabama","County":"Jefferson ","City":"Pleasant Grove city"},
{"State":"Alabama","County":"Jefferson ","City":"Sumiton city"},
{"State":"Alabama","County":"Jefferson ","City":"Sylvan Springs"},
{"State":"Alabama","County":"Jefferson ","City":"Tarrant city"},
{"State":"Alabama","County":"Jefferson ","City":"Trafford"},
{"State":"Alabama","County":"Jefferson ","City":"Trussville city"},
{"State":"Alabama","County":"Jefferson ","City":"Vestavia Hills city"},
{"State":"Alabama","County":"Jefferson ","City":"Warrior city"},
{"State":"Alabama","County":"Jefferson ","City":"West Jefferson"},
{"State":"Alabama","County":"Lamar ","City":"Beaverton"},
{"State":"Alabama","County":"Lamar ","City":"Detroit"},
{"State":"Alabama","County":"Lamar ","City":"Kennedy"},
{"State":"Alabama","County":"Lamar ","City":"Millport"},
{"State":"Alabama","County":"Lamar ","City":"Sulligent city"},
{"State":"Alabama","County":"Lamar ","City":"Vernon city"},
{"State":"Alabama","County":"Lauderdale ","City":"Anderson"},
{"State":"Alabama","County":"Lauderdale ","City":"Florence city"},
{"State":"Alabama","County":"Lauderdale ","City":"Killen"},
{"State":"Alabama","County":"Lauderdale ","City":"Lexington"},
{"State":"Alabama","County":"Lauderdale ","City":"Rogersville"},
{"State":"Alabama","County":"Lauderdale ","City":"St. Florian"},
{"State":"Alabama","County":"Lauderdale ","City":"Waterloo"},
{"State":"Alabama","County":"Lawrence ","City":"Courtland"},
{"State":"Alabama","County":"Lawrence ","City":"Hillsboro"},
{"State":"Alabama","County":"Lawrence ","City":"Moulton city"},
{"State":"Alabama","County":"Lawrence ","City":"North Courtland"},
{"State":"Alabama","County":"Lawrence ","City":"Town Creek"},
{"State":"Alabama","County":"Lee ","City":"Auburn city"},
{"State":"Alabama","County":"Lee ","City":"Loachapoka"},
{"State":"Alabama","County":"Lee ","City":"Notasulga"},
{"State":"Alabama","County":"Lee ","City":"Opelika city"},
{"State":"Alabama","County":"Lee ","City":"Phenix City city"},
{"State":"Alabama","County":"Lee ","City":"Smiths Station city"},
{"State":"Alabama","County":"Lee ","City":"Waverly"},
{"State":"Alabama","County":"Limestone ","City":"Ardmore"},
{"State":"Alabama","County":"Limestone ","City":"Athens city"},
{"State":"Alabama","County":"Limestone ","City":"Decatur city"},
{"State":"Alabama","County":"Limestone ","City":"Elkmont"},
{"State":"Alabama","County":"Limestone ","City":"Huntsville city"},
{"State":"Alabama","County":"Limestone ","City":"Lester"},
{"State":"Alabama","County":"Limestone ","City":"Madison city"},
{"State":"Alabama","County":"Limestone ","City":"Mooresville"},
{"State":"Alabama","County":"Lowndes ","City":"Benton"},
{"State":"Alabama","County":"Lowndes ","City":"Fort Deposit"},
{"State":"Alabama","County":"Lowndes ","City":"Gordonville"},
{"State":"Alabama","County":"Lowndes ","City":"Hayneville"},
{"State":"Alabama","County":"Lowndes ","City":"Lowndesboro"},
{"State":"Alabama","County":"Lowndes ","City":"Mosses"},
{"State":"Alabama","County":"Lowndes ","City":"White Hall"},
{"State":"Alabama","County":"Macon ","City":"Franklin"},
{"State":"Alabama","County":"Macon ","City":"Notasulga"},
{"State":"Alabama","County":"Macon ","City":"Shorter"},
{"State":"Alabama","County":"Macon ","City":"Tuskegee city"},
{"State":"Alabama","County":"Madison ","City":"Gurley"},
{"State":"Alabama","County":"Madison ","City":"Huntsville city"},
{"State":"Alabama","County":"Madison ","City":"Madison city"},
{"State":"Alabama","County":"Madison ","City":"New Hope city"},
{"State":"Alabama","County":"Madison ","City":"Owens Cross Roads"},
{"State":"Alabama","County":"Madison ","City":"Triana"},
{"State":"Alabama","County":"Marengo ","City":"Dayton"},
{"State":"Alabama","County":"Marengo ","City":"Demopolis city"},
{"State":"Alabama","County":"Marengo ","City":"Faunsdale"},
{"State":"Alabama","County":"Marengo ","City":"Linden city"},
{"State":"Alabama","County":"Marengo ","City":"Myrtlewood"},
{"State":"Alabama","County":"Marengo ","City":"Providence"},
{"State":"Alabama","County":"Marengo ","City":"Sweet Water"},
{"State":"Alabama","County":"Marengo ","City":"Thomaston"},
{"State":"Alabama","County":"Marion ","City":"Bear Creek"},
{"State":"Alabama","County":"Marion ","City":"Brilliant"},
{"State":"Alabama","County":"Marion ","City":"Glen Allen"},
{"State":"Alabama","County":"Marion ","City":"Guin city"},
{"State":"Alabama","County":"Marion ","City":"Gu-Win"},
{"State":"Alabama","County":"Marion ","City":"Hackleburg"},
{"State":"Alabama","County":"Marion ","City":"Haleyville city"},
{"State":"Alabama","County":"Marion ","City":"Hamilton city"},
{"State":"Alabama","County":"Marion ","City":"Twin"},
{"State":"Alabama","County":"Marion ","City":"Winfield city"},
{"State":"Alabama","County":"Marshall ","City":"Albertville city"},
{"State":"Alabama","County":"Marshall ","City":"Arab city"},
{"State":"Alabama","County":"Marshall ","City":"Boaz city"},
{"State":"Alabama","County":"Marshall ","City":"Douglas"},
{"State":"Alabama","County":"Marshall ","City":"Grant"},
{"State":"Alabama","County":"Marshall ","City":"Guntersville city"},
{"State":"Alabama","County":"Marshall ","City":"Sardis City"},
{"State":"Alabama","County":"Marshall ","City":"Union Grove"},
{"State":"Alabama","County":"Mobile ","City":"Bayou La Batre city"},
{"State":"Alabama","County":"Mobile ","City":"Chickasaw city"},
{"State":"Alabama","County":"Mobile ","City":"Citronelle city"},
{"State":"Alabama","County":"Mobile ","City":"Creola city"},
{"State":"Alabama","County":"Mobile ","City":"Dauphin Island"},
{"State":"Alabama","County":"Mobile ","City":"Mobile city"},
{"State":"Alabama","County":"Mobile ","City":"Mount Vernon"},
{"State":"Alabama","County":"Mobile ","City":"Prichard city"},
{"State":"Alabama","County":"Mobile ","City":"Saraland city"},
{"State":"Alabama","County":"Mobile ","City":"Satsuma city"},
{"State":"Alabama","County":"Monroe ","City":"Beatrice"},
{"State":"Alabama","County":"Monroe ","City":"Excel"},
{"State":"Alabama","County":"Monroe ","City":"Frisco City"},
{"State":"Alabama","County":"Monroe ","City":"Monroeville city"},
{"State":"Alabama","County":"Monroe ","City":"Vredenburgh"},
{"State":"Alabama","County":"Montgomery ","City":"Montgomery city"},
{"State":"Alabama","County":"Montgomery ","City":"Pike Road"},
{"State":"Alabama","County":"Morgan ","City":"Decatur city"},
{"State":"Alabama","County":"Morgan ","City":"Eva"},
{"State":"Alabama","County":"Morgan ","City":"Falkville"},
{"State":"Alabama","County":"Morgan ","City":"Hartselle city"},
{"State":"Alabama","County":"Morgan ","City":"Priceville"},
{"State":"Alabama","County":"Morgan ","City":"Somerville"},
{"State":"Alabama","County":"Morgan ","City":"Trinity"},
{"State":"Alabama","County":"Perry ","City":"Marion city"},
{"State":"Alabama","County":"Perry ","City":"Uniontown"},
{"State":"Alabama","County":"Pickens ","City":"Aliceville city"},
{"State":"Alabama","County":"Pickens ","City":"Carrollton"},
{"State":"Alabama","County":"Pickens ","City":"Ethelsville"},
{"State":"Alabama","County":"Pickens ","City":"Gordo"},
{"State":"Alabama","County":"Pickens ","City":"McMullen"},
{"State":"Alabama","County":"Pickens ","City":"Memphis"},
{"State":"Alabama","County":"Pickens ","City":"Pickensville"},
{"State":"Alabama","County":"Pickens ","City":"Reform"},
{"State":"Alabama","County":"Pike ","City":"Banks"},
{"State":"Alabama","County":"Pike ","City":"Brundidge city"},
{"State":"Alabama","County":"Pike ","City":"Goshen"},
{"State":"Alabama","County":"Pike ","City":"Troy city"},
{"State":"Alabama","County":"Randolph ","City":"Roanoke city"},
{"State":"Alabama","County":"Randolph ","City":"Wadley"},
{"State":"Alabama","County":"Randolph ","City":"Wedowee"},
{"State":"Alabama","County":"Randolph ","City":"Woodland"},
{"State":"Alabama","County":"Russell ","City":"Hurtsboro"},
{"State":"Alabama","County":"Russell ","City":"Phenix City city"},
{"State":"Alabama","County":"St. Clair ","City":"Argo"},
{"State":"Alabama","County":"St. Clair ","City":"Ashville city"},
{"State":"Alabama","County":"St. Clair ","City":"Leeds city"},
{"State":"Alabama","County":"St. Clair ","City":"Margaret"},
{"State":"Alabama","County":"St. Clair ","City":"Moody city"},
{"State":"Alabama","County":"St. Clair ","City":"Odenville"},
{"State":"Alabama","County":"St. Clair ","City":"Pell City city"},
{"State":"Alabama","County":"St. Clair ","City":"Ragland"},
{"State":"Alabama","County":"St. Clair ","City":"Riverside"},
{"State":"Alabama","County":"St. Clair ","City":"Springville city"},
{"State":"Alabama","County":"St. Clair ","City":"Steele"},
{"State":"Alabama","County":"St. Clair ","City":"Trussville city"},
{"State":"Alabama","County":"St. Clair ","City":"Vincent"},
{"State":"Alabama","County":"Shelby ","City":"Alabaster city"},
{"State":"Alabama","County":"Shelby ","City":"Birmingham city"},
{"State":"Alabama","County":"Shelby ","City":"Calera city"},
{"State":"Alabama","County":"Shelby ","City":"Chelsea city"},
{"State":"Alabama","County":"Shelby ","City":"Columbiana city"},
{"State":"Alabama","County":"Shelby ","City":"Harpersville"},
{"State":"Alabama","County":"Shelby ","City":"Helena city"},
{"State":"Alabama","County":"Shelby ","City":"Hoover city"},
{"State":"Alabama","County":"Shelby ","City":"Indian Springs Village city"},
{"State":"Alabama","County":"Shelby ","City":"Leeds city"},
{"State":"Alabama","County":"Shelby ","City":"Montevallo city"},
{"State":"Alabama","County":"Shelby ","City":"Pelham city"},
{"State":"Alabama","County":"Shelby ","City":"Vestavia Hills city"},
{"State":"Alabama","County":"Shelby ","City":"Vincent"},
{"State":"Alabama","County":"Shelby ","City":"Westover"},
{"State":"Alabama","County":"Shelby ","City":"Wilsonville"},
{"State":"Alabama","County":"Shelby ","City":"Wilton"},
{"State":"Alabama","County":"Sumter ","City":"Cuba"},
{"State":"Alabama","County":"Sumter ","City":"Emelle"},
{"State":"Alabama","County":"Sumter ","City":"Epes"},
{"State":"Alabama","County":"Sumter ","City":"Gainesville"},
{"State":"Alabama","County":"Sumter ","City":"Geiger"},
{"State":"Alabama","County":"Sumter ","City":"Livingston city"},
{"State":"Alabama","County":"Sumter ","City":"York city"},
{"State":"Alabama","County":"Talladega ","City":"Bon Air"},
{"State":"Alabama","County":"Talladega ","City":"Childersburg city"},
{"State":"Alabama","County":"Talladega ","City":"Lincoln city"},
{"State":"Alabama","County":"Talladega ","City":"Munford"},
{"State":"Alabama","County":"Talladega ","City":"Oak Grove"},
{"State":"Alabama","County":"Talladega ","City":"Oxford city"},
{"State":"Alabama","County":"Talladega ","City":"Sylacauga city"},
{"State":"Alabama","County":"Talladega ","City":"Talladega city"},
{"State":"Alabama","County":"Talladega ","City":"Talladega Springs"},
{"State":"Alabama","County":"Talladega ","City":"Vincent"},
{"State":"Alabama","County":"Talladega ","City":"Waldo"},
{"State":"Alabama","County":"Tallapoosa ","City":"Alexander City city"},
{"State":"Alabama","County":"Tallapoosa ","City":"Camp Hill"},
{"State":"Alabama","County":"Tallapoosa ","City":"Dadeville city"},
{"State":"Alabama","County":"Tallapoosa ","City":"Daviston"},
{"State":"Alabama","County":"Tallapoosa ","City":"Goldville"},
{"State":"Alabama","County":"Tallapoosa ","City":"Jacksons' Gap"},
{"State":"Alabama","County":"Tallapoosa ","City":"New Site"},
{"State":"Alabama","County":"Tallapoosa ","City":"Tallassee city"},
{"State":"Alabama","County":"Tuscaloosa ","City":"Brookwood"},
{"State":"Alabama","County":"Tuscaloosa ","City":"Coaling"},
{"State":"Alabama","County":"Tuscaloosa ","City":"Coker"},
{"State":"Alabama","County":"Tuscaloosa ","City":"Lake View"},
{"State":"Alabama","County":"Tuscaloosa ","City":"Moundville"},
{"State":"Alabama","County":"Tuscaloosa ","City":"Northport city"},
{"State":"Alabama","County":"Tuscaloosa ","City":"Tuscaloosa city"},
{"State":"Alabama","County":"Tuscaloosa ","City":"Vance"},
{"State":"Alabama","County":"Tuscaloosa ","City":"Woodstock"},
{"State":"Alabama","County":"Walker ","City":"Carbon Hill city"},
{"State":"Alabama","County":"Walker ","City":"Cordova city"},
{"State":"Alabama","County":"Walker ","City":"Dora city"},
{"State":"Alabama","County":"Walker ","City":"Eldridge"},
{"State":"Alabama","County":"Walker ","City":"Jasper city"},
{"State":"Alabama","County":"Walker ","City":"Kansas"},
{"State":"Alabama","County":"Walker ","City":"Nauvoo"},
{"State":"Alabama","County":"Walker ","City":"Oakman"},
{"State":"Alabama","County":"Walker ","City":"Parrish"},
{"State":"Alabama","County":"Walker ","City":"Sipsey"},
{"State":"Alabama","County":"Walker ","City":"Sumiton city"},
{"State":"Alabama","County":"Washington ","City":"Chatom"},
{"State":"Alabama","County":"Washington ","City":"McIntosh"},
{"State":"Alabama","County":"Washington ","City":"Millry"},
{"State":"Alabama","County":"Wilcox ","City":"Camden city"},
{"State":"Alabama","County":"Wilcox ","City":"Oak Hill"},
{"State":"Alabama","County":"Wilcox ","City":"Pine Apple"},
{"State":"Alabama","County":"Wilcox ","City":"Pine Hill"},
{"State":"Alabama","County":"Wilcox ","City":"Yellow Bluff"},
{"State":"Alabama","County":"Winston ","City":"Addison"},
{"State":"Alabama","County":"Winston ","City":"Arley"},
{"State":"Alabama","County":"Winston ","City":"Double Springs"},
{"State":"Alabama","County":"Winston ","City":"Haleyville city"},
{"State":"Alabama","County":"Winston ","City":"Lynn"},
{"State":"Alabama","County":"Winston ","City":"Natural Bridge"},
{"State":"Alabama","County":"Winston ","City":"Nauvoo"}];