var alaska = [{"State":"Alaska","County":"Aleutians East Borough","City":"Akutan city"},
{"State":"Alaska","County":"Aleutians East Borough","City":"Cold Bay city"},
{"State":"Alaska","County":"Aleutians East Borough","City":"False Pass city"},
{"State":"Alaska","County":"Aleutians East Borough","City":"King Cove city"},
{"State":"Alaska","County":"Aleutians East Borough","City":"Sand Point city"},
{"State":"Alaska","County":"Aleutians West Census Area","City":"Adak city"},
{"State":"Alaska","County":"Aleutians West Census Area","City":"Atka city"},
{"State":"Alaska","County":"Aleutians West Census Area","City":"St. George city"},
{"State":"Alaska","County":"Aleutians West Census Area","City":"St. Paul city"},
{"State":"Alaska","County":"Aleutians West Census Area","City":"Unalaska city"},
{"State":"Alaska","County":"Anchorage Municipality","City":"Anchorage municipality"},
{"State":"Alaska","County":"Bethel Census Area","City":"Akiak city"},
{"State":"Alaska","County":"Bethel Census Area","City":"Aniak city"},
{"State":"Alaska","County":"Bethel Census Area","City":"Bethel city"},
{"State":"Alaska","County":"Bethel Census Area","City":"Chefornak city"},
{"State":"Alaska","County":"Bethel Census Area","City":"Chuathbaluk city"},
{"State":"Alaska","County":"Bethel Census Area","City":"Eek city"},
{"State":"Alaska","County":"Bethel Census Area","City":"Goodnews Bay city"},
{"State":"Alaska","County":"Bethel Census Area","City":"Kwethluk city"},
{"State":"Alaska","County":"Bethel Census Area","City":"Lower Kalskag city"},
{"State":"Alaska","County":"Bethel Census Area","City":"Mekoryuk city"},
{"State":"Alaska","County":"Bethel Census Area","City":"Napakiak city"},
{"State":"Alaska","County":"Bethel Census Area","City":"Napaskiak city"},
{"State":"Alaska","County":"Bethel Census Area","City":"Nightmute city"},
{"State":"Alaska","County":"Bethel Census Area","City":"Nunapitchuk city"},
{"State":"Alaska","County":"Bethel Census Area","City":"Platinum city"},
{"State":"Alaska","County":"Bethel Census Area","City":"Quinhagak city"},
{"State":"Alaska","County":"Bethel Census Area","City":"Toksook Bay city"},
{"State":"Alaska","County":"Bethel Census Area","City":"Upper Kalskag city"},
{"State":"Alaska","County":"Denali Borough","City":"Anderson city"},
{"State":"Alaska","County":"Dillingham Census Area","City":"Aleknagik city"},
{"State":"Alaska","County":"Dillingham Census Area","City":"Clark's Point city"},
{"State":"Alaska","County":"Dillingham Census Area","City":"Dillingham city"},
{"State":"Alaska","County":"Dillingham Census Area","City":"Ekwok city"},
{"State":"Alaska","County":"Dillingham Census Area","City":"Manokotak city"},
{"State":"Alaska","County":"Dillingham Census Area","City":"New Stuyahok city"},
{"State":"Alaska","County":"Dillingham Census Area","City":"Togiak city"},
{"State":"Alaska","County":"Fairbanks North Star Borough","City":"Fairbanks city"},
{"State":"Alaska","County":"Fairbanks North Star Borough","City":"North Pole city"},
{"State":"Alaska","County":"Hoonah-Angoon Census Area","City":"Angoon city"},
{"State":"Alaska","County":"Hoonah-Angoon Census Area","City":"Gustavus city"},
{"State":"Alaska","County":"Hoonah-Angoon Census Area","City":"Hoonah city"},
{"State":"Alaska","County":"Hoonah-Angoon Census Area","City":"Pelican city"},
{"State":"Alaska","County":"Hoonah-Angoon Census Area","City":"Tenakee Springs city"},
{"State":"Alaska","County":"Juneau City and Borough","City":"Juneau city and borough"},
{"State":"Alaska","County":"Kenai Peninsula Borough","City":"Homer city"},
{"State":"Alaska","County":"Kenai Peninsula Borough","City":"Kachemak city"},
{"State":"Alaska","County":"Kenai Peninsula Borough","City":"Kenai city"},
{"State":"Alaska","County":"Kenai Peninsula Borough","City":"Seldovia city"},
{"State":"Alaska","County":"Kenai Peninsula Borough","City":"Seward city"},
{"State":"Alaska","County":"Kenai Peninsula Borough","City":"Soldotna city"},
{"State":"Alaska","County":"Ketchikan Gateway Borough","City":"Ketchikan city"},
{"State":"Alaska","County":"Ketchikan Gateway Borough","City":"Saxman city"},
{"State":"Alaska","County":"Kodiak Island Borough","City":"Akhiok city"},
{"State":"Alaska","County":"Kodiak Island Borough","City":"Kodiak city"},
{"State":"Alaska","County":"Kodiak Island Borough","City":"Larsen Bay city"},
{"State":"Alaska","County":"Kodiak Island Borough","City":"Old Harbor city"},
{"State":"Alaska","County":"Kodiak Island Borough","City":"Ouzinkie city"},
{"State":"Alaska","County":"Kodiak Island Borough","City":"Port Lions city"},
{"State":"Alaska","County":"Lake and Peninsula Borough","City":"Chignik city"},
{"State":"Alaska","County":"Lake and Peninsula Borough","City":"Egegik city"},
{"State":"Alaska","County":"Lake and Peninsula Borough","City":"Newhalen city"},
{"State":"Alaska","County":"Lake and Peninsula Borough","City":"Nondalton city"},
{"State":"Alaska","County":"Lake and Peninsula Borough","City":"Pilot Point city"},
{"State":"Alaska","County":"Lake and Peninsula Borough","City":"Port Heiden city"},
{"State":"Alaska","County":"Matanuska-Susitna Borough","City":"Houston city"},
{"State":"Alaska","County":"Matanuska-Susitna Borough","City":"Palmer city"},
{"State":"Alaska","County":"Matanuska-Susitna Borough","City":"Wasilla city"},
{"State":"Alaska","County":"Nome Census Area","City":"Brevig Mission city"},
{"State":"Alaska","County":"Nome Census Area","City":"Diomede city"},
{"State":"Alaska","County":"Nome Census Area","City":"Elim city"},
{"State":"Alaska","County":"Nome Census Area","City":"Gambell city"},
{"State":"Alaska","County":"Nome Census Area","City":"Golovin city"},
{"State":"Alaska","County":"Nome Census Area","City":"Koyuk city"},
{"State":"Alaska","County":"Nome Census Area","City":"Nome city"},
{"State":"Alaska","County":"Nome Census Area","City":"St. Michael city"},
{"State":"Alaska","County":"Nome Census Area","City":"Savoonga city"},
{"State":"Alaska","County":"Nome Census Area","City":"Shaktoolik city"},
{"State":"Alaska","County":"Nome Census Area","City":"Shishmaref city"},
{"State":"Alaska","County":"Nome Census Area","City":"Stebbins city"},
{"State":"Alaska","County":"Nome Census Area","City":"Teller city"},
{"State":"Alaska","County":"Nome Census Area","City":"Unalakleet city"},
{"State":"Alaska","County":"Nome Census Area","City":"Wales city"},
{"State":"Alaska","County":"Nome Census Area","City":"White Mountain city"},
{"State":"Alaska","County":"North Slope Borough","City":"Anaktuvuk Pass city"},
{"State":"Alaska","County":"North Slope Borough","City":"Atqasuk city"},
{"State":"Alaska","County":"North Slope Borough","City":"Barrow city"},
{"State":"Alaska","County":"North Slope Borough","City":"Kaktovik city"},
{"State":"Alaska","County":"North Slope Borough","City":"Nuiqsut city"},
{"State":"Alaska","County":"North Slope Borough","City":"Point Hope city"},
{"State":"Alaska","County":"North Slope Borough","City":"Wainwright city"},
{"State":"Alaska","County":"Northwest Arctic Borough","City":"Ambler city"},
{"State":"Alaska","County":"Northwest Arctic Borough","City":"Buckland city"},
{"State":"Alaska","County":"Northwest Arctic Borough","City":"Deering city"},
{"State":"Alaska","County":"Northwest Arctic Borough","City":"Kiana city"},
{"State":"Alaska","County":"Northwest Arctic Borough","City":"Kivalina city"},
{"State":"Alaska","County":"Northwest Arctic Borough","City":"Kobuk city"},
{"State":"Alaska","County":"Northwest Arctic Borough","City":"Kotzebue city"},
{"State":"Alaska","County":"Northwest Arctic Borough","City":"Noorvik city"},
{"State":"Alaska","County":"Northwest Arctic Borough","City":"Selawik city"},
{"State":"Alaska","County":"Northwest Arctic Borough","City":"Shungnak city"},
{"State":"Alaska","County":"Petersburg Census Area","City":"Kake city"},
{"State":"Alaska","County":"Petersburg Census Area","City":"Kupreanof city"},
{"State":"Alaska","County":"Petersburg Census Area","City":"Petersburg city"},
{"State":"Alaska","County":"Petersburg Census Area","City":"Port Alexander city"},
{"State":"Alaska","County":"Prince of Wales-Hyder Census Area","City":"Coffman Cove city"},
{"State":"Alaska","County":"Prince of Wales-Hyder Census Area","City":"Craig city"},
{"State":"Alaska","County":"Prince of Wales-Hyder Census Area","City":"Hydaburg city"},
{"State":"Alaska","County":"Prince of Wales-Hyder Census Area","City":"Kasaan city"},
{"State":"Alaska","County":"Prince of Wales-Hyder Census Area","City":"Klawock city"},
{"State":"Alaska","County":"Prince of Wales-Hyder Census Area","City":"Thorne Bay city"},
{"State":"Alaska","County":"Sitka City and Borough","City":"Sitka city and borough"},
{"State":"Alaska","County":"Southeast Fairbanks Census Area","City":"Delta Junction city"},
{"State":"Alaska","County":"Southeast Fairbanks Census Area","City":"Eagle city"},
{"State":"Alaska","County":"Valdez-Cordova Census Area","City":"Cordova city"},
{"State":"Alaska","County":"Valdez-Cordova Census Area","City":"Valdez city"},
{"State":"Alaska","County":"Valdez-Cordova Census Area","City":"Whittier city"},
{"State":"Alaska","County":"Wade Hampton Census Area","City":"Alakanuk city"},
{"State":"Alaska","County":"Wade Hampton Census Area","City":"Chevak city"},
{"State":"Alaska","County":"Wade Hampton Census Area","City":"Emmonak city"},
{"State":"Alaska","County":"Wade Hampton Census Area","City":"Hooper Bay city"},
{"State":"Alaska","County":"Wade Hampton Census Area","City":"Kotlik city"},
{"State":"Alaska","County":"Wade Hampton Census Area","City":"Marshall city"},
{"State":"Alaska","County":"Wade Hampton Census Area","City":"Mountain Village city"},
{"State":"Alaska","County":"Wade Hampton Census Area","City":"Nunam Iqua city"},
{"State":"Alaska","County":"Wade Hampton Census Area","City":"Pilot Station city"},
{"State":"Alaska","County":"Wade Hampton Census Area","City":"Russian Mission city"},
{"State":"Alaska","County":"Wade Hampton Census Area","City":"St. Mary's city"},
{"State":"Alaska","County":"Wade Hampton Census Area","City":"Scammon Bay city"},
{"State":"Alaska","County":"Wrangell City and Borough","City":"Wrangell city and borough"},
{"State":"Alaska","County":"Yukon-Koyukuk Census Area","City":"Allakaket city"},
{"State":"Alaska","County":"Yukon-Koyukuk Census Area","City":"Anvik city"},
{"State":"Alaska","County":"Yukon-Koyukuk Census Area","City":"Bettles city"},
{"State":"Alaska","County":"Yukon-Koyukuk Census Area","City":"Fort Yukon city"},
{"State":"Alaska","County":"Yukon-Koyukuk Census Area","City":"Galena city"},
{"State":"Alaska","County":"Yukon-Koyukuk Census Area","City":"Grayling city"},
{"State":"Alaska","County":"Yukon-Koyukuk Census Area","City":"Holy Cross city"},
{"State":"Alaska","County":"Yukon-Koyukuk Census Area","City":"Hughes city"},
{"State":"Alaska","County":"Yukon-Koyukuk Census Area","City":"Huslia city"},
{"State":"Alaska","County":"Yukon-Koyukuk Census Area","City":"Kaltag city"},
{"State":"Alaska","County":"Yukon-Koyukuk Census Area","City":"Koyukuk city"},
{"State":"Alaska","County":"Yukon-Koyukuk Census Area","City":"McGrath city"},
{"State":"Alaska","County":"Yukon-Koyukuk Census Area","City":"Nenana city"},
{"State":"Alaska","County":"Yukon-Koyukuk Census Area","City":"Nikolai city"},
{"State":"Alaska","County":"Yukon-Koyukuk Census Area","City":"Nulato city"},
{"State":"Alaska","County":"Yukon-Koyukuk Census Area","City":"Ruby city"},
{"State":"Alaska","County":"Yukon-Koyukuk Census Area","City":"Shageluk city"},
{"State":"Alaska","County":"Yukon-Koyukuk Census Area","City":"Tanana city"}]
